### ISSUE TITLE
Suggestion: Automatically join guildname group

### ISSUE THREAD

**Issue by S0T0** [viktorgullmark/exilence-next#488]
**Is your feature request related to a problem? Please describe.**
It'd be really nice to automatically have the program parse the Guild you're currently in and attempt to join it based on an default login. Such as <CoolGuild879>:<NoPassword>

**Describe the solution you'd like**
-- This should probably be disabled in settings by default to save resources for those that don't need to use it --
1. Parse data from from the default accounts profile for pathofexile to obtain the guildName its current in
2. Attempt to join a group by that name, if not create the group without an password.

**Describe alternatives you've considered**
That's about it really, not sure how hard it would be to implement as it'd be a workaround right now if it's time consuming to fix https://github.com/viktorgullmark/exilence-next/issues/487#issue-581362329

**Additional context**

**Comment by viktorgullmark** [comment]
Thanks for the suggestion!

We don't really want autojoin functionality when launching the app, since the app is not purely made for groups. However, we could have some option to persist groups (see https://github.com/viktorgullmark/exilence-next/issues/487), but more than that seems niche in my opinion, at least at the moment.

The guild scenario would assume most people use this within guilds, which we have no data on yet. If this turns out to be the case we could consider something like this.

I'll close this for now.

**Comment by sbsrnt** [comment]
Duplicate https://github.com/viktorgullmark/exilence-next/issues/371
