### ISSUE TITLE
Price Map stash tab?

### ISSUE THREAD

**Issue by domagojmedo** [viktorgullmark/exilence-next#533]
I don't see this mentioned anywhere, but I can't add map stash tab to track it.
Is it a bug or are map tabs not supported?

**Comment by justin-capalbo** [comment]
For some reason the get stash tabs API doesn't return items for map tabs.  This data as far as I was aware last time I tried to write my own tool is only available through the public stash tab API that POE trade uses to index items in public tabs.  But I'm not sure if setting your map tab to public is enough for Exilience because afaik the public tab system isn't something that you can just look for a particular person's public tabs - it's a massive feed of data.  Please correct me if i'm wrong.

**Comment by tamaroth** [comment]
This would also explain why you cannot see the contents of your map stash tab when browsing your stash on pathofexile.com.

Thank you for the explanation @justin-capalbo!

**Comment by viktorgullmark** [comment]
This is correct. We only use the character-window API (the pathofexile.com website) right now. Go there and select the maptab yourself, and you will see it has no contents.

We are not going to implement a solution using the public stash tab API, at least for now.

GGG has said multiple times that it's on their todo list to fix this, but probably far down on that list.
