### ISSUE TITLE
There should be an option to select all tabs in a league

### ISSUE THREAD

**Issue by chinhodado** [viktorgullmark/exilence-next#554]
**Is your feature request related to a problem? Please describe.**
I have hundreds of tabs in Standard. I can't manually select each and every one of them from the dropdown list, it would take forever.

**Describe the solution you'd like**
Add a radio box that says "All tabs in this league"

**Comment by viktorgullmark** [comment]
We want to discourage this behaviour since it greatly increases the snapshot time, and many users dont expect this, and will blame the app being slow. If you have 100 tabs it would take many minutes for just one snapshot to complete.

With that said, we will consider this and see how we can warn the user more and if we can implement something like this.
