### ISSUE TITLE
Dont count oils below Opalescent 

### ISSUE THREAD

**Issue by vadash** [viktorgullmark/exilence-next#568]
As blight farmer I have a lot of oils and exilence incorrectly price them. Its real price is close to 0

**Comment by korey-enright** [comment]
You can set a minimum threshold price in the settings menu, accessible from the left navigation pane. That being said it may be a good idea to add a feature to remove tracking specific items since it does seem that ninja has difficulty pricing them and black oils at least are worth around 2 chaos on the official trade site. They have plenty of listings, so excluding low confidence prices doesn't help.

**Comment by viktorgullmark** [comment]
Exilence or poe.ninja? If the price is not the same as poe.ninja, feel free to re open, but we dont do the pricing ourselves so if the actual price is wrong, its most likely on poe.ninjas end and not related to Exilence itself.
