### ISSUE TITLE
Remember on which screen programm is

### ISSUE THREAD

**Issue by Smeagol001** [viktorgullmark/exilence-next#593]
id like to see  that the prog remembers  on which screen it was when it was closed.

**Comment by sbsrnt** [comment]
Not sure if I get it right.

Currently it does remember when you close it, either minimizing to tray or jus quitting the app. It also remembers when PC goes to sleep so is this related to restarting PC?

@viktorgullmark you may be familiar with this suggestion due to https://github.com/viktorgullmark/exilence-next/issues/507

**Comment by viktorgullmark** [comment]
Yup, we have an issue for the overlay listed. Its quiet easy to implement, we can do it the same way as we remember sizes for the main window.

**Comment by viktorgullmark** [comment]
Closing since @sbsrnt linked the related issue, feel free to follow that one instead!

**Comment by Smeagol001** [comment]
for me if i close exilence it doesnt seem to save the windowposition of either overlay or programm though it allways starts at my primary monitor and i have to move it to my other monitor

**Comment by viktorgullmark** [comment]
It should be fixed with the next update (0.3.15), if the issue persists through 0.3.15, feel free to reopen this and we will take a look! 👍
