### ISSUE TITLE
Nothing Happens on Opening .Exe?

### ISSUE THREAD

**Issue by abowman02** [viktorgullmark/exilence-next#614]
When I click on the .exe to install onto Windows 10, it loads for a second then stops and nothing happens. No screen pops up at any point or anything. Are there some prerequisite programs I am missing? I have the latest node.js

**Comment by viktorgullmark** [comment]
1. Uninstall Exilence Next from your pc
2. Download the latest release from releases
3. Install the latest release and try again

No prerequisites needed, its bundled as an exe.

**Comment by abowman02** [comment]
Unfortunately, I cannot uninstall it as there is nothing installed. I have looked with the default windows program un/installer as well as third party programs and nothing appears. There is nothing in the directory where I tried to open it. Like I said, nothing visibly happens when I try to run it. I downloaded the exe multiple times as well as the zip file. I am at a loss.

**Comment by viktorgullmark** [comment]
I believe this is a case where your firewall/antivirus blocks the program since its released from an unknown publisher. We do not have a code signing certificate since they are very expensive and this is a freeware. You could check if the exe is blocked somewhere on your PC. 

Unfortunately this is related to your environment and not the application, but try the above to see if it helps.

**Comment by viktorgullmark** [comment]
Closing this. If you still experience problems, let us know in our Discord (link in the README.md file).
