### ISSUE TITLE
Auto rejoin group on open

### ISSUE THREAD

**Issue by ChaosDMG** [viktorgullmark/exilence-next#657]
**Is your feature request related to a problem? Please describe.**
When you close and reopen you need to manually rejoin the group.

**Describe the solution you'd like**
Save the group you are in and auto rejoin on open (would also be nice to have inactive members still show up).

**Comment by Saik19922** [comment]
Seconding this, two groups in our guild that would profit im terms of QoL out of this.

**Comment by Vaniquin** [comment]
Seconding this. I'm playing in a guild and we're playing in groups. We really could need this in terms of QoL.

**Comment by GregBe** [comment]
+1 the current implementation is kinda useless if you have to create a new groupe everytime why cant we rejoint the last groupe we were in?

**Comment by viktorgullmark** [comment]
https://github.com/viktorgullmark/exilence-next/issues/487

Closing this one since its a duplicate. We have some features in mind for the grouping system in general, but we need to rework it a bit from the ground up so this will not be something we can add to the next update sadly, since its not a very straightforward fix.

**Comment by sbsrnt** [comment]
Duplicate https://github.com/viktorgullmark/exilence-next/issues/371
