### ISSUE TITLE
Since the new update v0.5.1 it no longer possible to fetch the price from the league, only standard and HC

### ISSUE THREAD

**Issue by RushInNow95** [viktorgullmark/exilence-next#705]
As in the title. Photo as reference. https://imgur.com/a/ZRDPtXz

**Comment by sbsrnt** [comment]
To clarify, as we just had this discussion on discord.

This issue only applies to characters that are in private league and were not yet created or migrated to seasonal league.

This is an oversight on our end and as a workaround all you have to do is to create lvl 1 character (no need to log into the game) in either Expedition or Expedition HC (or both).

To clarify this change:
Previously what we were doing is we were fetching prices for all 4 leagues: _standard_, _hardcore_, _seasonal league_ and _seasonal hardcore league_. Even when PoE account didn't have characters for said leagues.

As an example: 
You are playing only on standard and you only care about standard league. Snapshotting happens, where we fetch stashes and calculate prices. Instead of only downloading data for standard, we are downloading data for all 4 leagues that you may not really care about thus slowing down *thrice* the process of fetching step.


Now we only download data to leagues you have characters in. So if you are curious about prices in other leagues you have to create new character in the league you are interested in seeing the prices.

Seems like a hurdle for those who actually may be curious in checking how items are priced in other leagues so I will implement a QoL checkbox that will have this functionality as `optional` so we can have best of both worlds.
