### ISSUE TITLE
Custom Pricing Option?

### ISSUE THREAD

**Issue by TheFryon** [viktorgullmark/exilence-next#728]
**Is your feature request related to a problem? Please describe.**
Hello i was going throught today looking at stuff that was inflating total value today such as low tier div cards and say top left bottom right sac frags, went to reprice them and finding items in 13500 listings is kinda hard, mainly because u cant filter by say Divination cards. 

**Describe the solution you'd like**
Was wondering if its at all possible to add something to the profile section to right click an item and "set value to (x)" or even "ignore this item". Completely clueless when it comes to coding, sorry if this isnt as simple as it seems, has been asked multiple times, or there is already a simplified way im to dumb to seem to see.

**Comment by viktorgullmark** [comment]
This already exists in the settings (the cogwheel in the leftmost menu, or by clicking "customize prices" in the item table). Closing, let me know if it doesnt work :)

**Comment by TheFryon** [comment]
this is "the list of 13500 items that is hard to navigate when trying to ignore over valued div cards and such" i was referring to

**Comment by viktorgullmark** [comment]
In 0.6.0 we added support for RegEx filtering in the filter section, so you should be able to filter on most attributes (cant recall exactly which), which means it should be possible to display only divination cards with some filter.

However, I understand the issue but at the same time we do not want to bloat the profile section table too much, since we already display a lot of columns, hence why we opted for the customize prices button. 

I will revisit this to see if something can be done, but my initial feeling is that we will leave this as is for now.

**Comment by viktorgullmark** [comment]
This is the PR I was referring to with RegEx support: https://github.com/viktorgullmark/exilence-next/pull/712

**Comment by TheFryon** [comment]
or make it possible for this feature https://snipboard.io/xwA6kR.jpg to have a Tab specific option would work as well? also dont know how this works when it comes to coding >. < sorry for my pea brain suggestions.

**Comment by TheFryon** [comment]
Summary for anyone looking in the future possibly: 
A. Add right click pricing options to Profile section  https://snipboard.io/Uh1xsu.jpg
B. Add "div, card, divination" Tag to all div cards?
C. Make threshold feature https://snipboard.io/xwA6kR.jpg Have Tab specific related option
